.PHONY: clean All

All:
	@echo "----------Building project:[ Section11_Challenge - Debug ]----------"
	@cd "Section11_Challenge" && "$(MAKE)" -f  "Section11_Challenge.mk"
clean:
	@echo "----------Cleaning project:[ Section11_Challenge - Debug ]----------"
	@cd "Section11_Challenge" && "$(MAKE)" -f  "Section11_Challenge.mk" clean
