.PHONY: clean All

All:
	@echo "----------Building project:[ Section10_Assignment_One - Debug ]----------"
	@cd "Section10_Assignment_One" && "$(MAKE)" -f  "Section10_Assignment_One.mk"
clean:
	@echo "----------Cleaning project:[ Section10_Assignment_One - Debug ]----------"
	@cd "Section10_Assignment_One" && "$(MAKE)" -f  "Section10_Assignment_One.mk" clean
