.PHONY: clean All

All:
	@echo "----------Building project:[ Section12_Notes - Debug ]----------"
	@cd "Section12_Notes" && "$(MAKE)" -f  "Section12_Notes.mk"
clean:
	@echo "----------Cleaning project:[ Section12_Notes - Debug ]----------"
	@cd "Section12_Notes" && "$(MAKE)" -f  "Section12_Notes.mk" clean
