.PHONY: clean All

All:
	@echo "----------Building project:[ sortComparison - Debug ]----------"
	@cd "sortComparison" && "$(MAKE)" -f  "sortComparison.mk"
clean:
	@echo "----------Cleaning project:[ sortComparison - Debug ]----------"
	@cd "sortComparison" && "$(MAKE)" -f  "sortComparison.mk" clean
