.PHONY: clean All

All:
	@echo "----------Building project:[ Section6Notes - Debug ]----------"
	@cd "Section6Notes" && "$(MAKE)" -f  "Section6Notes.mk"
clean:
	@echo "----------Cleaning project:[ Section6Notes - Debug ]----------"
	@cd "Section6Notes" && "$(MAKE)" -f  "Section6Notes.mk" clean
