.PHONY: clean All

All:
	@echo "----------Building project:[ Section7_notes - Debug ]----------"
	@cd "Section7_notes" && "$(MAKE)" -f  "Section7_notes.mk"
clean:
	@echo "----------Cleaning project:[ Section7_notes - Debug ]----------"
	@cd "Section7_notes" && "$(MAKE)" -f  "Section7_notes.mk" clean
