.PHONY: clean All

All:
	@echo "----------Building project:[ Section9_Challenge - Debug ]----------"
	@cd "Section9_Challenge" && "$(MAKE)" -f  "Section9_Challenge.mk"
clean:
	@echo "----------Cleaning project:[ Section9_Challenge - Debug ]----------"
	@cd "Section9_Challenge" && "$(MAKE)" -f  "Section9_Challenge.mk" clean
