.PHONY: clean All

All:
	@echo "----------Building project:[ Section4Notes - Debug ]----------"
	@cd "Section4Notes" && "$(MAKE)" -f  "Section4Notes.mk"
clean:
	@echo "----------Cleaning project:[ Section4Notes - Debug ]----------"
	@cd "Section4Notes" && "$(MAKE)" -f  "Section4Notes.mk" clean
